version: '3'
services:
  rust-backend:           # Nombre de la imagen
    build: .              # Seleccionamos el Dockerfile en la raíz del proyecto
    image: rust-backend
    env_file:             # Leemos variables de entorno
      - .env
    ports:
      - "8080:8080"       # El primer puerto es para ingresar desde el navegador, el segundo el puerto configurado en el .env
    depends_on:
      - zookeeper
      - kafka
    restart: unless-stopped
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_1_NAME: develop
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: b-2.dev-global.8tdcju.c1.kafka.us-west-2.amazonaws.com:9092,b-3.dev-global.8tdcju.c1.kafka.us-west-2.amazonaws.com:9092,b-1.dev-global.8tdcju.c1.kafka.us-west-2.amazonaws.com:9092